apiVersion: v1
kind: Service
metadata:
  name: test-service
  namespace: default
  labels:
    app: test
spec:
  type: ClusterIP
  selector:
    app: test
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP